name: CI/CD Workflow - Shelf

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            cd ~/AppDev/www/production/web-shelf
          else
            cd ~/AppDev/www/staging/web-shelf
          fi
          
          git pull origin ${{ github.ref_name }}
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
          php artisan migrate --force
          php artisan shield:generate --all
          
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          php artisan optimize
          
          echo ${{ secrets.VPS_PASSWORD }} | sudo -S systemctl restart nginx
